name: dm_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.24.*
  - scipy=1.12.*
  - scikit-learn=1.6.*
  - matplotlib=3.9.*
  - numba=0.60.*
  - joblib=1.4.*
  - tqdm=4.67.*
  - ipython=8.12.*
  - ipykernel=6.29.*
  - psutil=5.9.*
  - pillow=11.1.*
  - pyqt=6.7.*
  - jax=0.3.25
  - jaxlib=0.3.25
  - cupy
  - pip
  - pip:
      - polars==1.27.1
      - derivative==0.6.3
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - fastrlock==0.8.3
      - git-filter-repo==2.47.0
      - pipdeptree==2.28.0