name: candyman_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.*
  - pip=22.1.*
  - numpy=1.21.*
  - scipy=1.7.*
  - scikit-learn=1.0.*
  - matplotlib=3.5.*
  - h5py=3.8.*
  - pyyaml=6.0.*
  - pillow=9.5.*
  - requests=2.31.*
  - urllib3=2.0.*
  - typing-extensions=4.7.*
  - setuptools
  - wheel
  - pip:
      - tensorflow==2.0.0
      - tensorflow-estimator==2.0.1
      - tensorboard==2.0.2
      - keras==2.3.1
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2

      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - oauthlib==3.2.2
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0

      - absl-py==2.1.0
      - astor==0.8.1
      - cachetools==4.2.4
      - gast==0.2.2
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - markdown==3.4.4
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - joblib==1.3.2
      - threadpoolctl==3.1.0
      - protobuf==3.20.3
      - importlib-metadata==6.7.0
      - zipp==3.15.0
      - termcolor==2.3.0
      - python-dateutil==2.9.0.post0
      - pyparsing==3.1.4
      - kiwisolver==1.4.5
      - fonttools==4.38.0
      - cycler==0.11.0
      - charset-normalizer==3.4.4
      - idna==3.10
      - certifi==2025.10.5

