name: ldnet_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip
  - numpy=1.22.*
  - scipy=1.7.*
  - pandas=1.4.*
  - matplotlib=3.5.*
  - ipython=8.18.*
  - ipykernel=6.30.*
  - jupyter_client=8.6.*
  - jupyter_core=5.8.*
  - psutil=7.0.*
  - packaging
  - setuptools
  - wheel
  - pip:
      - tensorflow==2.8.0
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tf-estimator-nightly==2.8.0.dev2021122109

      - requests==2.32.5
      - urllib3==2.5.0
      - pillow==11.3.0
      - protobuf==3.20.0
      - wrapt==2.0.0

      - google-auth==2.41.1
      - google-auth-oauthlib==0.4.6
      - oauthlib==3.3.1
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2

      - cycler==0.12.1
      - fonttools==4.60.1
      - kiwisolver==1.4.7
      - pyparsing==3.2.5
      - pytz==2025.2

      - charset-normalizer==3.4.4
      - idna==3.11
      - certifi==2025.10.5
      - werkzeug==3.1.3
      - markdown==3.9
      - markupsafe==3.0.3
      - cachetools==6.2.1

