name: node_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip

  - numpy=2.0.*
  - scipy=1.13.*

  - pytorch=2.5.1
  - torchdiffeq=0.2.2

  - networkx=3.2.*
  - sympy=1.14.*
  - mpmath=1.3.*
  - filelock=3.16.*
  - fsspec=2025.7.*
  - jinja2=3.1.*

  - typing_extensions=4.12.*
  - setuptools
  - wheel

  - pip:
      - matplotlib==3.9.4
      - pillow==11.3.0
      - python-dateutil==2.9.0.post0
      - six==1.17.0

